#!/bin/sh -e

if [ "$TIMEOUT" = "" ]; then
  TIMEOUT=86400
fi
BACKUPS=/backups
if [ "$PREFIX" = "" ]; then
  PREFIX="%Y-%m-%d_%H-%m-%S_"
fi
if [ "$SUFFIX" = "" ]; then
  SUFFIX=""
fi

BUCKET=$1
if [ -z "$BUCKET" ]
then
  echo "$0 bucket container [container...]"
  echo "(If set, docker-backup output will be POSTed to \$PUSHGATEWAY)"
  exit 1
fi
shift

if [ -z "$ACCESS_KEY" -o -z "$SECRET_KEY" ]
then
  echo "Please set ACCESS_KEY and SECRET_KEY environment variables"
  exit 1
fi


[ -d "$BACKUPS" ] || mkdir "$BACKUPS"

push_metrics() {
  [ -z "$PUSHGATEWAY" ] && return
  curl --data-binary @- "$PUSHGATEWAY"
}

backup() {
  echo "[=] $1"
  while true
  do
    sprefix=$(date +${PREFIX})
    ssuffix=$(date +${SUFFIX})
    tar=${sprefix}$1${ssuffix}.tar
    echo "BACKUP: $1 - file $tar"
    /docker-backup/docker-backup $OPTS -addr /docker.sock store "$BACKUPS/$tar" "$1" | push_metrics
    gzip "$BACKUPS/$tar"

    echo "UPLOAD: $1"
    s3cmd --access_key="$ACCESS_KEY" --secret_key="$SECRET_KEY" \
          -c /dev/null $S3CMD_OPTS put "$BACKUPS/$tar.gz" $BUCKET
    rm "$BACKUPS/$tar.gz"

    date +"last_run{container=\"$1\"} %s" | push_metrics
    echo "SLEEP: $1 for $TIMEOUT seconds"
    sleep $TIMEOUT
  done
}

for c in $@
do
  backup $c &
done

wait
