#!/bin/sh -e

TIMEOUT=86400 # 24 hours
BACKUPS=/backups

BUCKET=$1
if [ -z "$BUCKET" ]
then
  echo "$0 bucket container [container...]"
  echo "(If set, docker-backup output will be POSTed to \$PUSHGATEWAY)"
  exit 1
fi
shift

if [ -z "$ACCESS_KEY" -o -z "$SECRET_KEY" ]
then
  echo "Please set ACCESS_KEY and SECRET_KEY environment variables"
  exit 1
fi


[ -d "$BACKUPS" ] || mkdir "$BACKUPS"

push_metrics() {
  [ -z "$PUSHGATEWAY" ] && return
  curl --data-binary @- "$PUSHGATEWAY"
}

backup() {
  echo "[=] $1"
  while true
  do
    echo "$1: Backup"
    /docker-backup/docker-backup $OPTS -addr /docker.sock store "$BACKUPS/$1.tar" "$1" | push_metrics
    gzip "$BACKUPS/$1.tar"

    echo "$1: Upload"
    s3cmd --access_key="$ACCESS_KEY" --secret_key="$SECRET_KEY" \
          -c /dev/null $S3CMD_OPTS put "$BACKUPS/$1.tar.gz" $BUCKET
    rm "$BACKUPS/$1.tar.gz"

    date +"last_run{container=\"$1\"} %s" | push_metrics
    echo "$1: Sleep"
    sleep $TIMEOUT
  done
}

for c in $@
do
  backup $c &
done

wait
